"""
APEX / BENVIN Forex Market Data API

Phase 2 - Market Intelligence Foundation

This module is the public compatibility layer for Forex
market-data operations.

The implementation is now separated into:

    models.py
        Standardized market-data structures.

    provider.py
        External market-data providers.

    service.py
        Market-data business/service layer.

    cache.py
        Short-lived market-data caching.

IMPORTANT:

    This module ONLY retrieves market data.

    It does NOT:

        - place trades
        - modify trading accounts
        - generate trade signals
        - recommend entries
        - recommend exits
        - calculate position sizes
        - execute strategies

Existing code can continue using:

    from market.data import get_forex_quote

without needing to know the internal architecture.
"""

import json

from .provider import (
    COMMON_FOREX_PAIRS,
    SUPPORTED_CURRENCIES,
    normalize_forex_pair,
)

from .service import MarketDataService


# ============================================================
# SERVICE
# ============================================================

_market_service = MarketDataService()


# ============================================================
# PUBLIC HELPERS
# ============================================================

def forex_pair_to_provider_symbol(pair):
    """
    Convert a Forex pair into the current provider symbol.

    Example:

        EURUSD
            ↓
        EURUSD=X
    """

    normalized = normalize_forex_pair(
        pair
    )

    if normalized is None:
        return None

    return f"{normalized}=X"


def is_supported_forex_pair(pair):
    """
    Check whether a Forex pair is structurally valid.
    """

    return (
        normalize_forex_pair(
            pair
        ) is not None
    )


# ============================================================
# GET FOREX QUOTE
# ============================================================

def get_forex_quote(
    pair,
    *,
    data_range="1d",
    interval="5m",
    use_cache=True
):
    """
    Retrieve the latest available Forex quote.

    Example:

        get_forex_quote("EURUSD")

    The returned price is supplied by the external market
    provider and is not generated by the LLM.
    """

    return _market_service.get_forex_quote(
        pair,
        data_range=data_range,
        interval=interval,
        use_cache=use_cache
    )


# ============================================================
# MARKET DATA HEALTH
# ============================================================

def check_market_data():
    """
    Check whether the market-data service is operational.
    """

    return _market_service.check_market_data()


# ============================================================
# MODULE TEST
# ============================================================

if __name__ == "__main__":

    print("=" * 60)
    print("APEX / BENVIN FOREX MARKET DATA TEST")
    print("=" * 60)

    print()

    print("Provider:")
    print(
        _market_service.provider.name
    )

    print()

    print("Testing EURUSD:")

    result = get_forex_quote(
        "EURUSD",
        use_cache=False
    )

    print()

    print(
        json.dumps(
            result,
            indent=2,
            ensure_ascii=False
        )
    )

    print()

    print("=" * 60)
    print("MARKET DATA TEST COMPLETE")
    print("=" * 60)